In [1]:
import pandas as pd
import numpy as np

In [5]:
df1= pd.read_csv("Dataset\Reddit_Data.csv")
df2= pd.read_csv("Dataset\Twitter_Data.csv")

In [8]:
df1.head()

                                       clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

In [9]:
df2.head()

                                          clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [11]:
data = pd.concat([df1, df2], ignore_index = True)
data

,clean_comment,category,clean_text
0,family mormon have never tried explain them t...,1.0,NaN
1,buddhism has very much lot compatible with chr...,1.0,NaN
2,seriously don say thing first all they won get...,-1.0,NaN
3,what you have learned yours and only yours wha...,0.0,NaN
4,for your own benefit you may want read living ...,1.0,NaN
...,...,...,...
200224,NaN,-1.0,why these 456 crores paid neerav modi not reco...
200225,NaN,-1.0,dear rss terrorist payal gawar what about modi...
200226,NaN,0.0,did you cover her interaction forum where she ...
200227,NaN,0.0,there big project came into india modi dream p...
200228,NaN,1.0,have you ever listen about like gurukul where ...